# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_income'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kharj',
            new_name='KharjHa',
        ),
    ]
